# ============================================================
# PROJECT FINANCE EXCEL EXPORT
# ============================================================
#
# Purpose:
#   Export the EXACT project-finance inputs and calculations
#   generated by build_project_statement(project)
#
# Input:
#   project
#   analysis
#
# Output:
#   BytesIO Excel workbook
#
# ============================================================

from io import BytesIO
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
from openpyxl.utils import get_column_letter


# ============================================================
# COLORS / STYLES
# ============================================================

DARK_BLUE = "1F4E78"
BLUE = "D9EAF7"
LIGHT_BLUE = "EAF3F8"
GREY = "D9E1F2"
LIGHT_GREY = "F2F2F2"
GREEN = "E2F0D9"
YELLOW = "FFF2CC"
RED = "FCE4D6"
WHITE = "FFFFFF"
BLACK = "000000"

thin_border = Border(
    left=Side(style="thin", color="BFBFBF"),
    right=Side(style="thin", color="BFBFBF"),
    top=Side(style="thin", color="BFBFBF"),
    bottom=Side(style="thin", color="BFBFBF"),
)


# ============================================================
# BASIC HELPERS
# ============================================================

def safe(value, default=0):
    """
    Convert None to a usable value.
    Keep strings unchanged.
    """
    if value is None:
        return default
    return value


def number(value):
    """
    Numeric Excel value.
    """
    if value is None:
        return 0

    try:
        return float(value)
    except (TypeError, ValueError):
        return value


def fmt_number(cell):
    """
    Excel number formatting.
    """
    cell.number_format = '#,##0.00'


def fmt_percent(cell):
    cell.number_format = '0.00%'


def write_title(ws, row, title_text, end_col=10):
    """
    Writes a section title.
    """

    ws.merge_cells(
        start_row=row,
        start_column=1,
        end_row=row,
        end_column=max(1, end_col)
    )

    cell = ws.cell(row=row, column=1)
    cell.value = title_text

    cell.font = Font(
        bold=True,
        color=WHITE,
        size=12
    )

    cell.fill = PatternFill(
        "solid",
        fgColor=DARK_BLUE
    )

    cell.alignment = Alignment(
        horizontal="left"
    )

    return row


def write_header(ws, row, headers):
    """
    Writes a table header.

    IMPORTANT:
    This function is intentionally called write_header
    instead of header_row to avoid the previous:
        TypeError: 'int' object is not callable
    """

    for col, header in enumerate(headers, start=1):

        cell = ws.cell(
            row=row,
            column=col
        )

        cell.value = header

        cell.font = Font(
            bold=True,
            color=BLACK
        )

        cell.fill = PatternFill(
            "solid",
            fgColor=BLUE
        )

        cell.border = thin_border

        cell.alignment = Alignment(
            horizontal="center",
            vertical="center"
        )

    return row


def write_cell(ws, row, col, value, numeric=False):
    """
    Writes one cell.
    """

    cell = ws.cell(
        row=row,
        column=col
    )

    if numeric:
        cell.value = number(value)
        fmt_number(cell)
    else:
        cell.value = safe(value, "")

    cell.border = thin_border

    return cell


def auto_width(ws, minimum=12, maximum=35):
    """
    Automatically size columns.
    """

    for column_cells in ws.columns:

        length = 0

        column_letter = get_column_letter(
            column_cells[0].column
        )

        for cell in column_cells:

            try:
                value_length = len(
                    str(cell.value)
                )
            except Exception:
                value_length = 0

            length = max(
                length,
                value_length
            )

        ws.column_dimensions[
            column_letter
        ].width = max(
            minimum,
            min(length + 2, maximum)
        )


def freeze(ws, cell="B5"):
    ws.freeze_panes = cell


def style_total_row(ws, row, start_col=1, end_col=None):

    if end_col is None:
        end_col = ws.max_column

    for col in range(start_col, end_col + 1):

        cell = ws.cell(
            row=row,
            column=col
        )

        cell.font = Font(
            bold=True
        )

        cell.fill = PatternFill(
            "solid",
            fgColor=LIGHT_BLUE
        )

        cell.border = thin_border


def add_year_headers(ws, row, project_life):

    headers = ["Particulars"]

    for year in range(1, project_life + 1):
        headers.append(
            f"Year {year}"
        )

    write_header(
        ws,
        row,
        headers
    )

    return row


# ============================================================
# PROJECT SUMMARY
# ============================================================

def build_summary_sheet(wb, project, analysis):

    ws = wb.create_sheet("Project Summary")

    write_title(
        ws,
        1,
        "PROJECT FINANCE SUMMARY",
        4
    )

    rows = [
        ("Project Name", getattr(project, "name", "")),
        ("Project Type", getattr(project, "project_type", "")),
        ("Project Life", getattr(project, "project_life", 0)),
        (
            "Construction Period (Months)",
            getattr(project, "construction_period_months", 0)
        ),
        ("Tax Rate", getattr(project, "tax_rate", 0)),
        ("Interest Rate", getattr(project, "interest_rate", 0)),
        ("Loan Tenor", getattr(project, "loan_tenor", 0)),
        (
            "Repayment Frequency",
            getattr(project, "repayment_frequency", "")
        ),
        (
            "Repayment Type",
            getattr(project, "repayment_type", "")
        ),
        (
            "Moratorium (Months)",
            getattr(project, "moratorium_months", 0)
        ),
        (
            "Interest Capitalized",
            getattr(project, "interest_capitalized", False)
        ),
    ]

    row = 3

    for label, value in rows:

        ws.cell(row=row, column=1).value = label
        ws.cell(row=row, column=1).font = Font(bold=True)

        ws.cell(row=row, column=2).value = value

        ws.cell(row=row, column=1).border = thin_border
        ws.cell(row=row, column=2).border = thin_border

        row += 1

    # --------------------------------------------------------
    # Analysis summary
    # --------------------------------------------------------

    projection = analysis.get(
        "projection",
        []
    )

    row += 2

    write_title(
        ws,
        row,
        "KEY PROJECT OUTPUTS",
        4
    )

    row += 2

    headers = [
        "Metric",
        "Year 1",
        "Year 2",
        "Year 3",
        "Project Life"
    ]

    write_header(
        ws,
        row,
        headers
    )

    metrics = [
        ("Revenue", "revenue"),
        ("EBITDA", "ebitda"),
        ("EBIT", "ebit"),
        ("EBT", "ebt"),
        ("PAT", "pat"),
        ("Cash Flow from Operations", "cashflow_operations"),
        ("Cash Flow from Investing", "cashflow_investing"),
        ("Cash Flow from Financing", "cashflow_financing"),
        ("Closing Cash", "closing_cash"),
        ("Closing Debt", "closing_debt"),
        ("Total Assets", "total_assets"),
        ("Total Liabilities", "total_liabilities"),
        ("Total Equity", "total_equity"),
        ("Balance Sheet Gap", "balance_sheet_gap"),
    ]

    row += 1

    for label, key in metrics:

        ws.cell(row=row, column=1).value = label

        for col in range(2, 5):

            index = col - 2

            if index < len(projection):

                value = projection[index].get(
                    key,
                    0
                )

            else:
                value = 0

            cell = ws.cell(
                row=row,
                column=col
            )

            cell.value = number(value)
            fmt_number(cell)

        # Project-life / final-year value

        if projection:

            value = projection[-1].get(
                key,
                0
            )

        else:
            value = 0

        cell = ws.cell(
            row=row,
            column=5
        )

        cell.value = number(value)
        fmt_number(cell)

        row += 1

    auto_width(ws)

    freeze(ws, "B3")

    return ws


# ============================================================
# REVENUE ASSUMPTIONS
# ============================================================

def build_revenue_assumptions_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "Revenue Assumptions"
    )

    write_title(
        ws,
        1,
        "REVENUE ASSUMPTIONS",
        17
    )

    headers = [
        "Name",
        "Type",
        "Amount",
        "Growth",
        "Capacity MW",
        "Operating Hours",
        "CUF",
        "Tariff",
        "Tariff Escalation",
        "Degradation",
        "Rooms",
        "Occupancy %",
        "ADR",
        "Food %",
        "Banquet %",
        "Spa %",
        "Other %"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for item in getattr(
        project,
        "revenue_items",
        []
    ):

        values = [
            getattr(item, "name", ""),
            getattr(item, "revenue_type", ""),
            getattr(item, "amount", 0),
            getattr(item, "growth_rate", 0),
            getattr(item, "capacity_mw", 0),
            getattr(item, "operating_hours", 0),
            getattr(item, "cuf", 0),
            getattr(item, "tariff", 0),
            getattr(item, "tariff_escalation", 0),
            getattr(item, "degradation_rate", 0),
            getattr(item, "rooms", 0),
            getattr(item, "occupancy_pct", 0),
            getattr(item, "adr", 0),
            getattr(item, "food_revenue_pct", 0),
            getattr(item, "banquet_revenue_pct", 0),
            getattr(item, "spa_revenue_pct", 0),
            getattr(item, "other_revenue_pct", 0),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col == 1 or col == 2:
                cell.value = safe(
                    value,
                    ""
                )
            else:
                cell.value = number(value)
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    if row == 4:
        ws.cell(
            row=row,
            column=1
        ).value = "No revenue assumptions found."

    auto_width(ws)

    freeze(ws, "A4")

    return ws


# ============================================================
# COGS ASSUMPTIONS
# ============================================================

def build_cogs_assumptions_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "COGS Assumptions"
    )

    write_title(
        ws,
        1,
        "COGS ASSUMPTIONS",
        6
    )

    headers = [
        "Name",
        "Type",
        "Amount",
        "Growth",
        "Cost / kWh",
        "Cost / Room"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for item in getattr(
        project,
        "cogs_items",
        []
    ):

        values = [
            getattr(item, "name", ""),
            getattr(item, "cogs_type", ""),
            getattr(item, "amount", 0),
            getattr(item, "growth_rate", 0),
            getattr(item, "cost_per_kwh", 0),
            getattr(item, "cost_per_room", 0),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col <= 2:
                cell.value = safe(
                    value,
                    ""
                )
            else:
                cell.value = number(value)
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    auto_width(ws)

    freeze(ws, "A4")

    return ws


# ============================================================
# OPEX ASSUMPTIONS
# ============================================================

def build_opex_assumptions_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "Opex Assumptions"
    )

    write_title(
        ws,
        1,
        "OPERATING EXPENSE ASSUMPTIONS",
        4
    )

    headers = [
        "Name",
        "Amount",
        "Escalation",
        "Type"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for item in getattr(
        project,
        "opex_items",
        []
    ):

        values = [
            getattr(item, "name", ""),
            getattr(item, "amount", 0),
            getattr(item, "escalation_rate", 0),
            getattr(item, "opex_type", ""),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col == 1 or col == 4:
                cell.value = safe(
                    value,
                    ""
                )
            else:
                cell.value = number(value)
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    auto_width(ws)

    freeze(ws, "A4")

    return ws


# ============================================================
# DEBT ASSUMPTIONS
# ============================================================

def build_debt_assumptions_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "Debt Assumptions"
    )

    write_title(
        ws,
        1,
        "DEBT ASSUMPTIONS",
        5
    )

    headers = [
        "Drawdown Year",
        "Drawdown Month",
        "Drawdown Amount",
        "Repayment Frequency",
        "Repayment Type"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for item in getattr(
        project,
        "debt_drawdowns",
        []
    ):

        values = [
            getattr(item, "year", 0),
            getattr(item, "drawdown_months", 0),
            getattr(item, "drawdown_amount", 0),
            getattr(
                project,
                "repayment_frequency",
                ""
            ),
            getattr(
                project,
                "repayment_type",
                ""
            )
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col >= 3 and col != 4 and col != 5:
                cell.value = number(value)
                fmt_number(cell)
            else:
                cell.value = safe(
                    value,
                    ""
                )

            cell.border = thin_border

        row += 1

    # Project-level debt information

    row += 2

    write_title(
        ws,
        row,
        "DEBT PARAMETERS",
        3
    )

    row += 2

    debt_params = [
        ("Interest Rate", getattr(project, "interest_rate", 0)),
        ("Loan Tenor", getattr(project, "loan_tenor", 0)),
        ("Moratorium Months", getattr(project, "moratorium_months", 0)),
        (
            "Interest Capitalized",
            getattr(project, "interest_capitalized", False)
        ),
    ]

    for label, value in debt_params:

        ws.cell(
            row=row,
            column=1
        ).value = label

        ws.cell(
            row=row,
            column=1
        ).font = Font(bold=True)

        ws.cell(
            row=row,
            column=2
        ).value = value

        ws.cell(
            row=row,
            column=1
        ).border = thin_border

        ws.cell(
            row=row,
            column=2
        ).border = thin_border

        if isinstance(value, (int, float)):

            fmt_number(
                ws.cell(
                    row=row,
                    column=2
                )
            )

        row += 1

    auto_width(ws)

    return ws


# ============================================================
# EQUITY ASSUMPTIONS
# ============================================================

def build_equity_assumptions_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "Equity Assumptions"
    )

    write_title(
        ws,
        1,
        "EQUITY ASSUMPTIONS",
        4
    )

    headers = [
        "Name",
        "Amount",
        "Growth",
        "Type"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for item in getattr(
        project,
        "equity_items",
        []
    ):

        values = [
            getattr(item, "name", ""),
            getattr(item, "amount", 0),
            getattr(item, "growth_rate", 0),
            getattr(item, "equity_type", ""),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col == 1 or col == 4:
                cell.value = safe(
                    value,
                    ""
                )
            else:
                cell.value = number(value)
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    auto_width(ws)

    return ws


# ============================================================
# ASSET INPUTS
# ============================================================

def build_asset_inputs_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "Asset Inputs"
    )

    write_title(
        ws,
        1,
        "FIXED ASSET INPUTS",
        12
    )

    headers = [
        "Asset Name",
        "Category",
        "Purchase Cost",
        "Purchase Year",
        "Sale Year",
        "Useful Life",
        "Salvage Value",
        "Depreciation Method",
        "Depreciation Rate",
        "Is Land"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    assets = getattr(
        project,
        "fixed_assets",
        []
    )

    for item in assets:

        values = [
            getattr(item, "asset_name", ""),
            getattr(item, "asset_category", ""),
            getattr(item, "purchase_cost", 0),
            getattr(item, "purchase_year", 0),
            getattr(item, "sale_year", 0),
            getattr(item, "useful_life", 0),
            getattr(item, "salvage_value", 0),
            getattr(item, "depreciation_method", ""),
            getattr(item, "depreciation_rate", 0),
            getattr(item, "is_land", False),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col in [1, 2, 8, 10]:
                cell.value = safe(
                    value,
                    ""
                )
            else:
                cell.value = number(value)
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    auto_width(ws)

    return ws


# ============================================================
# ASSET / LIABILITY / EQUITY OTHER ITEMS
# ============================================================

def build_balance_input_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "Other BS Inputs"
    )

    write_title(
        ws,
        1,
        "OTHER BALANCE SHEET INPUTS",
        5
    )

    # --------------------------------------------------------
    # Assets
    # --------------------------------------------------------

    write_title(
        ws,
        3,
        "ASSET ITEMS",
        4
    )

    write_header(
        ws,
        4,
        [
            "Name",
            "Type",
            "Amount",
            "Growth"
        ]
    )

    row = 5

    for item in getattr(
        project,
        "asset_items",
        []
    ):

        values = [
            getattr(item, "name", ""),
            getattr(item, "asset_type", ""),
            getattr(item, "amount", 0),
            getattr(item, "growth_rate", 0),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col <= 2:
                cell.value = safe(
                    value,
                    ""
                )
            else:
                cell.value = number(value)
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    # --------------------------------------------------------
    # Liabilities
    # --------------------------------------------------------

    row += 2

    write_title(
        ws,
        row,
        "LIABILITY ITEMS",
        4
    )

    row += 1

    write_header(
        ws,
        row,
        [
            "Name",
            "Type",
            "Amount",
            "Growth"
        ]
    )

    row += 1

    for item in getattr(
        project,
        "liability_items",
        []
    ):

        values = [
            getattr(item, "name", ""),
            getattr(item, "liability_type", ""),
            getattr(item, "amount", 0),
            getattr(item, "growth_rate", 0),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            if col <= 2:
                cell.value = safe(
                    value,
                    ""
                )
            else:
                cell.value = number(value)
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    auto_width(ws)

    return ws


# ============================================================
# WORKING CAPITAL ASSUMPTIONS
# ============================================================

def build_working_capital_assumptions_sheet(
    wb,
    project
):

    ws = wb.create_sheet(
        "Working Capital"
    )

    write_title(
        ws,
        1,
        "WORKING CAPITAL ASSUMPTIONS",
        4
    )

    wc = getattr(
        project,
        "working_capital",
        None
    )

    headers = [
        "Assumption",
        "Value",
        "Growth / Rate",
        "Unit"
    ]

    write_header(
        ws,
        3,
        headers
    )

    assumptions = []

    if wc:

        assumptions = [
            (
                "Receivable Days",
                getattr(wc, "receivable_days", 0),
                "",
                "Days"
            ),
            (
                "Inventory Days",
                getattr(wc, "inventory_days", 0),
                "",
                "Days"
            ),
            (
                "Payable Days",
                getattr(wc, "payable_days", 0),
                "",
                "Days"
            ),
            (
                "Prepaid Expenses",
                getattr(wc, "prepaid_expenses", 0),
                getattr(
                    wc,
                    "prepaid_growth_rate",
                    0
                ),
                "Amount"
            ),
            (
                "Other Current Assets",
                getattr(wc, "other_current_assets", 0),
                getattr(
                    wc,
                    "other_current_assets_growth_rate",
                    0
                ),
                "Amount"
            ),
            (
                "Other Current Liabilities",
                getattr(
                    wc,
                    "other_current_liabilities",
                    0
                ),
                getattr(
                    wc,
                    "other_current_liabilities_growth_rate",
                    0
                ),
                "Amount"
            ),
        ]

    row = 4

    for label, value, growth, unit in assumptions:

        ws.cell(
            row=row,
            column=1
        ).value = label

        ws.cell(
            row=row,
            column=2
        ).value = number(value)

        ws.cell(
            row=row,
            column=3
        ).value = (
            number(growth)
            if growth != ""
            else ""
        )

        ws.cell(
            row=row,
            column=4
        ).value = unit

        for col in range(1, 5):

            ws.cell(
                row=row,
                column=col
            ).border = thin_border

        fmt_number(
            ws.cell(
                row=row,
                column=2
            )
        )

        if growth != "":
            fmt_number(
                ws.cell(
                    row=row,
                    column=3
                )
            )

        row += 1

    auto_width(ws)

    return ws


# ============================================================
# INCOME STATEMENT
# ============================================================

def build_income_statement_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "Income Statement"
    )

    projection = analysis.get(
        "projection",
        []
    )

    project_life = getattr(
        project,
        "project_life",
        len(projection)
    )

    write_title(
        ws,
        1,
        "PROJECT FINANCE INCOME STATEMENT",
        project_life + 1
    )

    add_year_headers(
        ws,
        3,
        project_life
    )

    rows = [
        ("Revenue", "revenue"),
        ("COGS", "cogs"),
        ("Gross Profit", "gross_profit"),
        ("Operating Expenses", "opex"),
        ("EBITDA", "ebitda"),
        ("Depreciation", "depreciation"),
        ("EBIT", "ebit"),
        ("Interest Expense", "interest_expense"),
        ("EBT", "ebt"),
        ("Tax", "tax"),
        ("PAT", "pat"),
    ]

    row = 4

    for label, key in rows:

        ws.cell(
            row=row,
            column=1
        ).value = label

        for year in range(
            1,
            project_life + 1
        ):

            index = year - 1

            value = (
                projection[index].get(key, 0)
                if index < len(projection)
                else 0
            )

            cell = ws.cell(
                row=row,
                column=year + 1
            )

            cell.value = number(value)

            fmt_number(cell)

            cell.border = thin_border

        ws.cell(
            row=row,
            column=1
        ).border = thin_border

        if key in [
            "gross_profit",
            "ebitda",
            "ebit",
            "ebt",
            "pat"
        ]:

            style_total_row(
                ws,
                row,
                1,
                project_life + 1
            )

        row += 1

    auto_width(ws)

    freeze(ws, "B4")

    return ws


# ============================================================
# REVENUE DETAIL
# ============================================================

def build_revenue_detail_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "Revenue Detail"
    )

    projection = analysis.get(
        "projection",
        []
    )

    project_life = getattr(
        project,
        "project_life",
        len(projection)
    )

    write_title(
        ws,
        1,
        "REVENUE DETAIL",
        project_life + 5
    )

    headers = [
        "Revenue Item",
        "Type",
        "Metric"
    ]

    for year in range(
        1,
        project_life + 1
    ):
        headers.append(
            f"Year {year}"
        )

    write_header(
        ws,
        3,
        headers
    )

    # Gather every revenue item / metric appearing
    # in the backend result.

    detail_map = {}

    for year_index, p in enumerate(
        projection
    ):

        year = year_index + 1

        breakdown = p.get(
            "revenue_breakdown",
            {}
        )

        for item_name, data in breakdown.items():

            item_type = data.get(
                "type",
                ""
            )

            if item_name not in detail_map:
                detail_map[item_name] = {
                    "type": item_type,
                    "metrics": set()
                }

            for metric in data.keys():

                if metric != "type":

                    detail_map[
                        item_name
                    ]["metrics"].add(metric)

    row = 4

    for item_name, item_data in detail_map.items():

        item_type = item_data["type"]

        for metric in sorted(
            item_data["metrics"]
        ):

            ws.cell(
                row=row,
                column=1
            ).value = item_name

            ws.cell(
                row=row,
                column=2
            ).value = item_type

            ws.cell(
                row=row,
                column=3
            ).value = metric

            for year_index in range(
                project_life
            ):

                value = 0

                if year_index < len(projection):

                    breakdown = projection[
                        year_index
                    ].get(
                        "revenue_breakdown",
                        {}
                    )

                    data = breakdown.get(
                        item_name,
                        {}
                    )

                    value = data.get(
                        metric,
                        0
                    )

                cell = ws.cell(
                    row=row,
                    column=year_index + 4
                )

                cell.value = number(value)

                fmt_number(cell)

                cell.border = thin_border

            for col in range(1, 4):
                ws.cell(
                    row=row,
                    column=col
                ).border = thin_border

            row += 1

    auto_width(ws)

    return ws


# ============================================================
# COGS DETAIL
# ============================================================

def build_cogs_detail_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "COGS Detail"
    )

    projection = analysis.get(
        "projection",
        []
    )

    project_life = getattr(
        project,
        "project_life",
        len(projection)
    )

    write_title(
        ws,
        1,
        "COGS DETAIL",
        project_life + 4
    )

    headers = [
        "COGS Item",
        "Type",
        "Metric"
    ]

    for year in range(
        1,
        project_life + 1
    ):
        headers.append(
            f"Year {year}"
        )

    write_header(
        ws,
        3,
        headers
    )

    detail_map = {}

    for p in projection:

        breakdown = p.get(
            "cogs_breakdown",
            {}
        )

        for item_name, data in breakdown.items():

            if item_name not in detail_map:
                detail_map[item_name] = {
                    "type": data.get(
                        "type",
                        ""
                    ),
                    "metrics": set()
                }

            for metric in data.keys():

                if metric != "type":

                    detail_map[
                        item_name
                    ]["metrics"].add(metric)

    row = 4

    for item_name, item_data in detail_map.items():

        for metric in sorted(
            item_data["metrics"]
        ):

            ws.cell(
                row=row,
                column=1
            ).value = item_name

            ws.cell(
                row=row,
                column=2
            ).value = item_data["type"]

            ws.cell(
                row=row,
                column=3
            ).value = metric

            for year_index in range(
                project_life
            ):

                value = 0

                if year_index < len(projection):

                    breakdown = projection[
                        year_index
                    ].get(
                        "cogs_breakdown",
                        {}
                    )

                    data = breakdown.get(
                        item_name,
                        {}
                    )

                    value = data.get(
                        metric,
                        0
                    )

                cell = ws.cell(
                    row=row,
                    column=year_index + 4
                )

                cell.value = number(value)
                fmt_number(cell)
                cell.border = thin_border

            for col in range(1, 4):

                ws.cell(
                    row=row,
                    column=col
                ).border = thin_border

            row += 1

    auto_width(ws)

    return ws


# ============================================================
# OPEX DETAIL
# ============================================================

def build_opex_detail_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "Opex Detail"
    )

    projection = analysis.get(
        "projection",
        []
    )

    project_life = getattr(
        project,
        "project_life",
        len(projection)
    )

    write_title(
        ws,
        1,
        "OPERATING EXPENSE DETAIL",
        project_life + 2
    )

    headers = [
        "Opex Item",
        "Metric"
    ]

    for year in range(
        1,
        project_life + 1
    ):
        headers.append(
            f"Year {year}"
        )

    write_header(
        ws,
        3,
        headers
    )

    item_names = set()

    for p in projection:

        breakdown = p.get(
            "opex_breakdown",
            {}
        )

        item_names.update(
            breakdown.keys()
        )

    row = 4

    for item_name in sorted(
        item_names
    ):

        ws.cell(
            row=row,
            column=1
        ).value = item_name

        ws.cell(
            row=row,
            column=2
        ).value = "Expense"

        for year_index in range(
            project_life
        ):

            value = 0

            if year_index < len(projection):

                value = projection[
                    year_index
                ].get(
                    "opex_breakdown",
                    {}
                ).get(
                    item_name,
                    0
                )

            cell = ws.cell(
                row=row,
                column=year_index + 3
            )

            cell.value = number(value)
            fmt_number(cell)
            cell.border = thin_border

        ws.cell(
            row=row,
            column=1
        ).border = thin_border

        ws.cell(
            row=row,
            column=2
        ).border = thin_border

        row += 1

    auto_width(ws)

    return ws


# ============================================================
# CASH FLOW STATEMENT
# ============================================================

def build_cash_flow_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "Cash Flow"
    )

    projection = analysis.get(
        "projection",
        []
    )

    project_life = getattr(
        project,
        "project_life",
        len(projection)
    )

    write_title(
        ws,
        1,
        "PROJECT FINANCE CASH FLOW STATEMENT",
        project_life + 1
    )

    add_year_headers(
        ws,
        3,
        project_life
    )

    rows = [
        (
            "Cash Flow from Operations",
            "cashflow_operations"
        ),
        (
            "Cash Flow from Investing",
            "cashflow_investing"
        ),
        (
            "Cash Flow from Financing",
            "cashflow_financing"
        ),
        (
            "Capital Expenditure",
            "capex_outflow"
        ),
        (
            "Asset Sale Proceeds",
            "asset_sale_proceeds"
        ),
        (
            "Debt Drawn",
            "debt_drawn"
        ),
        (
            "Equity Drawn",
            "equity_drawn"
        ),
        (
            "Principal Repayment",
            "principal_repayment"
        ),
        (
            "Non-Current Asset Investment",
            "non_current_asset_investment"
        ),
        (
            "Non-Current Liability Change",
            "non_current_liability_change"
        ),
        (
            "Change in NWC",
            "change_in_nwc"
        ),
        (
            "Net Cash Flow",
            "net_cash_flow"
        ),
        (
            "Opening Cash",
            "opening_cash"
        ),
        (
            "Closing Cash",
            "closing_cash"
        ),
    ]

    row = 4

    for label, key in rows:

        ws.cell(
            row=row,
            column=1
        ).value = label

        for year in range(
            1,
            project_life + 1
        ):

            index = year - 1

            value = (
                projection[index].get(
                    key,
                    0
                )
                if index < len(projection)
                else 0
            )

            cell = ws.cell(
                row=row,
                column=year + 1
            )

            cell.value = number(value)
            fmt_number(cell)
            cell.border = thin_border

        ws.cell(
            row=row,
            column=1
        ).border = thin_border

        if key in [
            "cashflow_operations",
            "cashflow_investing",
            "cashflow_financing",
            "net_cash_flow",
            "closing_cash"
        ]:

            style_total_row(
                ws,
                row,
                1,
                project_life + 1
            )

        row += 1

    auto_width(ws)

    freeze(ws, "B4")

    return ws


# ============================================================
# BALANCE SHEET
# ============================================================

def build_balance_sheet_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "Balance Sheet"
    )

    projection = analysis.get(
        "projection",
        []
    )

    project_life = getattr(
        project,
        "project_life",
        len(projection)
    )

    write_title(
        ws,
        1,
        "PROJECT FINANCE BALANCE SHEET",
        project_life + 1
    )

    add_year_headers(
        ws,
        3,
        project_life
    )

    # --------------------------------------------------------
    # Collect every asset / liability / equity item
    # --------------------------------------------------------

    asset_keys = set()
    liability_keys = set()
    equity_keys = set()

    for p in projection:

        asset_keys.update(
            p.get(
                "asset_breakdown",
                {}
            ).keys()
        )

        liability_keys.update(
            p.get(
                "liability_breakdown",
                {}
            ).keys()
        )

        equity_keys.update(
            p.get(
                "equity_breakdown",
                {}
            ).keys()
        )

    # --------------------------------------------------------
    # ASSETS
    # --------------------------------------------------------

    row = 4

    ws.cell(
        row=row,
        column=1
    ).value = "ASSETS"

    ws.cell(
        row=row,
        column=1
    ).font = Font(
        bold=True
    )

    row += 1

    # Logical order

    preferred_asset_order = [
        "cash",
        "Accounts Receivable",
        "Inventory",
        "Prepaid Expenses",
        "Other Current Assets",
        "Gross PPE",
        "Capitalized IDC",
        "Gross Fixed Assets",
        "Accumulated Depreciation",
        "Net Fixed Assets",
    ]

    ordered_assets = []

    for key in preferred_asset_order:

        if key in asset_keys:
            ordered_assets.append(key)

    for key in sorted(asset_keys):

        if key not in ordered_assets:
            ordered_assets.append(key)

    for key in ordered_assets:

        ws.cell(
            row=row,
            column=1
        ).value = key

        for year in range(
            1,
            project_life + 1
        ):

            index = year - 1

            value = 0

            if index < len(projection):

                value = projection[
                    index
                ].get(
                    "asset_breakdown",
                    {}
                ).get(
                    key,
                    0
                )

            cell = ws.cell(
                row=row,
                column=year + 1
            )

            cell.value = number(value)
            fmt_number(cell)
            cell.border = thin_border

        ws.cell(
            row=row,
            column=1
        ).border = thin_border

        row += 1

    # Total assets

    ws.cell(
        row=row,
        column=1
    ).value = "TOTAL ASSETS"

    for year in range(
        1,
        project_life + 1
    ):

        index = year - 1

        value = (
            projection[index].get(
                "total_assets",
                0
            )
            if index < len(projection)
            else 0
        )

        cell = ws.cell(
            row=row,
            column=year + 1
        )

        cell.value = number(value)
        fmt_number(cell)

    style_total_row(
        ws,
        row,
        1,
        project_life + 1
    )

    row += 3

    # --------------------------------------------------------
    # LIABILITIES
    # --------------------------------------------------------

    ws.cell(
        row=row,
        column=1
    ).value = "LIABILITIES"

    ws.cell(
        row=row,
        column=1
    ).font = Font(
        bold=True
    )

    row += 1

    preferred_liability_order = [
        "Project Debt",
        "Accounts Payable",
        "Other Current Liabilities",
    ]

    ordered_liabilities = []

    for key in preferred_liability_order:

        if key in liability_keys:
            ordered_liabilities.append(key)

    for key in sorted(liability_keys):

        if key not in ordered_liabilities:
            ordered_liabilities.append(key)

    for key in ordered_liabilities:

        ws.cell(
            row=row,
            column=1
        ).value = key

        for year in range(
            1,
            project_life + 1
        ):

            index = year - 1

            value = 0

            if index < len(projection):

                value = projection[
                    index
                ].get(
                    "liability_breakdown",
                    {}
                ).get(
                    key,
                    0
                )

            cell = ws.cell(
                row=row,
                column=year + 1
            )

            cell.value = number(value)
            fmt_number(cell)
            cell.border = thin_border

        ws.cell(
            row=row,
            column=1
        ).border = thin_border

        row += 1

    ws.cell(
        row=row,
        column=1
    ).value = "TOTAL LIABILITIES"

    for year in range(
        1,
        project_life + 1
    ):

        index = year - 1

        value = (
            projection[index].get(
                "total_liabilities",
                0
            )
            if index < len(projection)
            else 0
        )

        cell = ws.cell(
            row=row,
            column=year + 1
        )

        cell.value = number(value)
        fmt_number(cell)

    style_total_row(
        ws,
        row,
        1,
        project_life + 1
    )

    row += 3

    # --------------------------------------------------------
    # EQUITY
    # --------------------------------------------------------

    ws.cell(
        row=row,
        column=1
    ).value = "EQUITY"

    ws.cell(
        row=row,
        column=1
    ).font = Font(
        bold=True
    )

    row += 1

    for key in sorted(
        equity_keys
    ):

        ws.cell(
            row=row,
            column=1
        ).value = key

        for year in range(
            1,
            project_life + 1
        ):

            index = year - 1

            value = 0

            if index < len(projection):

                value = projection[
                    index
                ].get(
                    "equity_breakdown",
                    {}
                ).get(
                    key,
                    0
                )

            cell = ws.cell(
                row=row,
                column=year + 1
            )

            cell.value = number(value)
            fmt_number(cell)
            cell.border = thin_border

        ws.cell(
            row=row,
            column=1
        ).border = thin_border

        row += 1

    ws.cell(
        row=row,
        column=1
    ).value = "TOTAL EQUITY"

    for year in range(
        1,
        project_life + 1
    ):

        index = year - 1

        value = (
            projection[index].get(
                "total_equity",
                0
            )
            if index < len(projection)
            else 0
        )

        cell = ws.cell(
            row=row,
            column=year + 1
        )

        cell.value = number(value)
        fmt_number(cell)

    style_total_row(
        ws,
        row,
        1,
        project_life + 1
    )

    row += 2

    # --------------------------------------------------------
    # CHECK
    # --------------------------------------------------------

    ws.cell(
        row=row,
        column=1
    ).value = "BALANCE SHEET GAP"

    for year in range(
        1,
        project_life + 1
    ):

        index = year - 1

        value = (
            projection[index].get(
                "balance_sheet_gap",
                0
            )
            if index < len(projection)
            else 0
        )

        cell = ws.cell(
            row=row,
            column=year + 1
        )

        cell.value = number(value)
        fmt_number(cell)

    style_total_row(
        ws,
        row,
        1,
        project_life + 1
    )

    auto_width(ws)

    freeze(ws, "B4")

    return ws


# ============================================================
# DEBT SCHEDULE
# ============================================================

def build_debt_schedule_sheet(
    wb,
    analysis
):

    ws = wb.create_sheet(
        "Debt Schedule"
    )

    debt_schedule = analysis.get(
        "debt_schedule",
        []
    )

    write_title(
        ws,
        1,
        "MONTHLY DEBT SCHEDULE",
        10
    )

    headers = [
        "Month",
        "Year",
        "Month of Year",
        "Drawdown",
        "Opening Balance",
        "Interest",
        "IDC",
        "Principal",
        "Debt Service",
        "Closing Balance"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for item in debt_schedule:

        values = [
            item.get("month", 0),
            item.get("year", 0),
            item.get("month_of_year", 0),
            item.get("drawdown", 0),
            item.get("opening_balance", 0),
            item.get("interest", 0),
            item.get("idc", 0),
            item.get("principal", 0),
            item.get("debt_service", 0),
            item.get("closing_balance", 0),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            cell.value = number(value)

            if col >= 4:
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    auto_width(ws)

    freeze(ws, "A4")

    return ws


# ============================================================
# ASSET SCHEDULE
# ============================================================

def build_asset_schedule_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "Asset Schedule"
    )

    asset_schedule = analysis.get(
        "asset_schedule",
        []
    )

    project_life = getattr(
        project,
        "project_life",
        len(asset_schedule)
    )

    write_title(
        ws,
        1,
        "FIXED ASSET SCHEDULE",
        11
    )

    headers = [
        "Year",
        "Asset Name",
        "Category",
        "Opening Cost",
        "Purchase",
        "Sale",
        "Closing Cost",
        "Opening Acc. Dep.",
        "Depreciation",
        "Closing Acc. Dep.",
        "Net Block"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for year_index in range(
        project_life
    ):

        if year_index >= len(
            asset_schedule
        ):
            break

        year_data = asset_schedule[
            year_index
        ]

        year = year_data.get(
            "year",
            year_index + 1
        )

        for asset in year_data.get(
            "assets",
            []
        ):

            values = [
                year,
                asset.get(
                    "asset_name",
                    ""
                ),
                asset.get(
                    "category",
                    ""
                ),
                asset.get(
                    "opening_cost",
                    0
                ),
                asset.get(
                    "purchase",
                    0
                ),
                asset.get(
                    "sale",
                    0
                ),
                asset.get(
                    "closing_cost",
                    0
                ),
                asset.get(
                    "opening_acc_dep",
                    0
                ),
                asset.get(
                    "depreciation",
                    0
                ),
                asset.get(
                    "closing_acc_dep",
                    0
                ),
                asset.get(
                    "net_block",
                    0
                ),
            ]

            for col, value in enumerate(
                values,
                start=1
            ):

                cell = ws.cell(
                    row=row,
                    column=col
                )

                if col in [2, 3]:
                    cell.value = safe(
                        value,
                        ""
                    )
                else:
                    cell.value = number(value)

                    if col >= 4:
                        fmt_number(cell)

                cell.border = thin_border

            row += 1

        # Total line

        totals = [
            "TOTAL",
            "",
            "",
            "",
            "",
            "",
            year_data.get(
                "total_gross_block",
                0
            ),
            "",
            "",
            year_data.get(
                "total_acc_dep",
                0
            ),
            year_data.get(
                "total_net_block",
                0
            ),
        ]

        for col, value in enumerate(
            totals,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            cell.value = value

            if isinstance(
                value,
                (int, float)
            ):
                fmt_number(cell)

            cell.border = thin_border

        style_total_row(
            ws,
            row,
            1,
            len(headers)
        )

        row += 1

    auto_width(ws)

    freeze(ws, "A4")

    return ws


# ============================================================
# WORKING CAPITAL SCHEDULE
# ============================================================

def build_working_capital_schedule_sheet(
    wb,
    analysis
):

    ws = wb.create_sheet(
        "WC Schedule"
    )

    projection = analysis.get(
        "projection",
        []
    )

    write_title(
        ws,
        1,
        "WORKING CAPITAL SCHEDULE",
        12
    )

    headers = [
        "Year",
        "Accounts Receivable",
        "Inventory",
        "Prepaid Expenses",
        "Other Current Assets",
        "Current Assets",
        "Accounts Payable",
        "Other Current Liabilities",
        "Current Liabilities",
        "NWC",
        "Change in NWC"
    ]

    write_header(
        ws,
        3,
        headers
    )

    row = 4

    for p in projection:

        wc = p.get(
            "working_capital_breakdown",
            {}
        )

        values = [
            p.get("year", 0),
            wc.get(
                "Accounts Receivable",
                0
            ),
            wc.get(
                "Inventory",
                0
            ),
            wc.get(
                "Prepaid Expenses",
                0
            ),
            wc.get(
                "Other Current Assets",
                0
            ),
            p.get(
                "current_assets",
                0
            ),
            wc.get(
                "Accounts Payable",
                0
            ),
            wc.get(
                "Other Current Liabilities",
                0
            ),
            p.get(
                "current_liabilities",
                0
            ),
            p.get(
                "nwc",
                0
            ),
            p.get(
                "change_in_nwc",
                0
            ),
        ]

        for col, value in enumerate(
            values,
            start=1
        ):

            cell = ws.cell(
                row=row,
                column=col
            )

            cell.value = number(value)

            if col >= 2:
                fmt_number(cell)

            cell.border = thin_border

        row += 1

    auto_width(ws)

    freeze(ws, "A4")

    return ws


# ============================================================
# YEARLY PROJECT STATEMENT - RAW DATA
# ============================================================

def build_raw_projection_sheet(
    wb,
    analysis,
    project
):

    ws = wb.create_sheet(
        "Raw Projection"
    )

    projection = analysis.get(
        "projection",
        []
    )

    write_title(
        ws,
        1,
        "RAW PROJECT STATEMENT OUTPUT",
        3
    )

    headers = [
        "Year",
        "Metric",
        "Value"
    ]

    write_header(
        ws,
        3,
        headers
    )

    # This sheet makes sure every scalar value
    # generated by build_project_statement is preserved.

    row = 4

    for p in projection:

        year = p.get(
            "year",
            row - 3
        )

        for key, value in p.items():

            if isinstance(
                value,
                (int, float)
            ):

                ws.cell(
                    row=row,
                    column=1
                ).value = year

                ws.cell(
                    row=row,
                    column=2
                ).value = key

                ws.cell(
                    row=row,
                    column=3
                ).value = number(value)

                fmt_number(
                    ws.cell(
                        row=row,
                        column=3
                    )
                )

                for col in range(1, 4):

                    ws.cell(
                        row=row,
                        column=col
                    ).border = thin_border

                row += 1

    auto_width(ws)

    freeze(ws, "A4")

    return ws


# ============================================================
# MAIN EXCEL BUILDER
# ============================================================

def build_project_finance_excel(
    project,
    analysis
):
    """
    Main Excel export function.

    This function intentionally DOES NOT recalculate
    the project.

    All statement numbers come from:

        build_project_statement(project)

    Therefore Excel reflects the exact backend output.
    """

    wb = Workbook()

    # Remove default worksheet

    default_ws = wb.active

    wb.remove(
        default_ws
    )

    # ========================================================
    # 1. SUMMARY
    # ========================================================

    build_summary_sheet(
        wb,
        project,
        analysis
    )

    # ========================================================
    # 2. INPUT / ASSUMPTION SHEETS
    # ========================================================

    build_revenue_assumptions_sheet(
        wb,
        project
    )

    build_cogs_assumptions_sheet(
        wb,
        project
    )

    build_opex_assumptions_sheet(
        wb,
        project
    )

    build_debt_assumptions_sheet(
        wb,
        project
    )

    build_equity_assumptions_sheet(
        wb,
        project
    )

    build_asset_inputs_sheet(
        wb,
        project
    )

    build_balance_input_sheet(
        wb,
        project
    )

    build_working_capital_assumptions_sheet(
        wb,
        project
    )

    # ========================================================
    # 3. FINANCIAL STATEMENTS
    # ========================================================

    build_income_statement_sheet(
        wb,
        analysis,
        project
    )

    build_cash_flow_sheet(
        wb,
        analysis,
        project
    )

    build_balance_sheet_sheet(
        wb,
        analysis,
        project
    )

    # ========================================================
    # 4. DETAILED SCHEDULES
    # ========================================================

    build_revenue_detail_sheet(
        wb,
        analysis,
        project
    )

    build_cogs_detail_sheet(
        wb,
        analysis,
        project
    )

    build_opex_detail_sheet(
        wb,
        analysis,
        project
    )

    build_debt_schedule_sheet(
        wb,
        analysis
    )

    build_asset_schedule_sheet(
        wb,
        analysis,
        project
    )

    build_working_capital_schedule_sheet(
        wb,
        analysis
    )

    # ========================================================
    # 5. RAW BACKEND OUTPUT
    # ========================================================

    build_raw_projection_sheet(
        wb,
        analysis,
        project
    )

    # ========================================================
    # GLOBAL FORMATTING
    # ========================================================

    for ws in wb.worksheets:

        ws.sheet_view.showGridLines = False

        # Make title row slightly taller

        if ws.max_row >= 1:
            ws.row_dimensions[1].height = 22

        # Vertical alignment

        for row in ws.iter_rows():

            for cell in row:

                cell.alignment = Alignment(
                    vertical="center"
                )

    # ========================================================
    # SAVE TO MEMORY
    # ========================================================

    output = BytesIO()

    wb.save(output)

    output.seek(0)

    return output